pointauc-token: "Bearer 0fc5b54d-7c6d-4e0e-bb08-86b11548e41b"
allowed-bid-amounts:
  - 1000
  - 5000
  - 10000
crystal-reward:
  min: 3
  max: 7
afk-farm-enabled: true
balance-autosave-interval-ticks: 600

database:
  # postgresql | sqlite
  type: postgresql
  postgresql:
    host: "31.57.34.237"
    port: "5432"
    name: "pointauc"
    username: "pointauc_user"
    password: "$8jZeJyHisphWWpPQ_F6"
  sqlite:
    # Relative to plugin data folder
    file: "test/pointauc.db"
